"""Property-based parity tests pinning Haute's _ExprEvaluator to real Polars.

Verifies that for every expression in a bounded grammar of documented, well-formed
single-row operations, the evaluator's result_value agrees with real Polars on
the same one-row frame (ENG-T11, closing the "no property-based testing" gap in
specs/expression-parsing/low-level.md).

Domain: numeric, boolean and string expressions of depth at most three over the
columns x and y (int, float or null) and s (string or null), built only from the
forms the evaluator documents. The one-row frame types a null cell by the value
family (Int64 for ints, Float64 for floats and nulls, String for s) so null
propagation is exercised through every operation instead of tripping Polars'
Null-dtype rejections. Malformed calls, window/aggregation forms and
unsupported methods are outside the domain; the classification tests below pin
their documented placeholder behaviour instead. A Polars evaluation that raises
on a generated form is assumed away; with the typed frame that happened for
none of 600 sampled examples on 2026-09-06.
"""

from __future__ import annotations

import ast
import math

import hypothesis.strategies as st
import polars as pl
import pytest
from hypothesis import assume, example, find, given

from haute._expression_parser import evaluate_expression
from tests._property_budget import pr_budget


def _trace_value(expr_text: str, row: dict) -> object:
    """result_value the trace renders for df.with_columns(<expr>.alias("out"))."""
    code = f'df = df.with_columns({expr_text}.alias("out"))'
    return evaluate_expression(code, "out", dict(row)).result_value


def _column_dtype(value: object) -> pl.DataType:
    """Type a one-row cell the way a real frame column would be typed."""
    if isinstance(value, bool):
        return pl.Boolean
    if isinstance(value, int):
        return pl.Int64
    if isinstance(value, str):
        return pl.String
    return pl.Float64


def _polars_value(expr_text: str, row: dict) -> object:
    """The engine's actual output for the same expression on a one-row frame.

    ``expr_text`` is generated by this module's own grammar (never user input),
    so ``eval`` is safe here. A null cell takes the numeric dtype of its column
    family (``s`` stays String) because a production frame carries a typed
    column with a null, not a Null-typed column.
    """
    expr = eval(expr_text, {"pl": pl})
    schema = {
        name: (pl.String if name == "s" else _column_dtype(value)) for name, value in row.items()
    }
    return pl.DataFrame([dict(row)], schema=schema).select(expr.alias("out")).item()


def values_equivalent(a: object, b: object) -> bool:
    """Check equivalence between evaluator trace value and Polars value.

    Equivalence rules:
    - both None -> equal
    - both bool -> ==
    - numbers (int/float) -> math.isclose(a, b, rel_tol=1e-9, abs_tol=1e-9)
      with NaN equal to NaN and infinities compared by identity/sign
    - strings -> ==
    - anything else -> ==
    """
    if a is None and b is None:
        return True
    if a is None or b is None:
        return False
    if isinstance(a, bool) or isinstance(b, bool):
        return isinstance(a, bool) and isinstance(b, bool) and a == b
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        if math.isnan(a) and math.isnan(b):
            return True
        if math.isnan(a) or math.isnan(b):
            return False
        if math.isinf(a) and math.isinf(b):
            return (a > 0) == (b > 0)
        if math.isinf(a) or math.isinf(b):
            return False
        return math.isclose(a, b, rel_tol=1e-9, abs_tol=1e-9)
    if isinstance(a, str) and isinstance(b, str):
        return a == b
    return a == b


# ---------------------------------------------------------------------------
# Grammar strategies
# ---------------------------------------------------------------------------

_num_literals = st.one_of(
    st.integers(min_value=-100, max_value=100),
    st.floats(min_value=-1e4, max_value=1e4, allow_nan=False, allow_infinity=False),
    st.integers(min_value=-2000, max_value=2000).map(lambda k: k / 8),
    st.integers(min_value=-2000, max_value=2000).map(lambda k: k / 100),
)

_num_leaves = st.one_of(
    st.just('pl.col("x")'),
    st.just('pl.col("y")'),
    _num_literals.map(lambda v: f"pl.lit({repr(v)})"),
)

_bounds = st.tuples(
    st.integers(min_value=-100, max_value=100),
    st.integers(min_value=-100, max_value=100),
).map(lambda p: (min(p), max(p)))

_closed_opts = st.sampled_from(["both", "left", "right", "none"])

_str_alphabet = "abcAB _-.0123456789"
_str_literals = st.text(alphabet=_str_alphabet, min_size=0, max_size=6)

_string_exprs = st.sampled_from(
    [
        'pl.col("s").str.to_lowercase()',
        'pl.col("s").str.to_uppercase()',
    ]
)

_non_zero_k = st.integers(min_value=-50, max_value=50).filter(lambda k: k != 0)


def _bool_exprs(e_strat: st.SearchStrategy[str]) -> st.SearchStrategy[str]:
    cmp_ops = ["<", "<=", ">", ">=", "==", "!="]
    comparisons = st.tuples(e_strat, st.sampled_from(cmp_ops), e_strat).map(
        lambda t: f"({t[0]} {t[1]} {t[2]})"
    )
    null_checks = st.one_of(
        e_strat.map(lambda e: f"{e}.is_null()"),
        e_strat.map(lambda e: f"{e}.is_not_null()"),
    )
    between_checks = st.one_of(
        st.tuples(e_strat, _bounds).map(lambda t: f"{t[0]}.is_between({t[1][0]}, {t[1][1]})"),
        st.tuples(e_strat, _bounds, _closed_opts).map(
            lambda t: f'{t[0]}.is_between({t[1][0]}, {t[1][1]}, closed="{t[2]}")'
        ),
    )
    in_checks = st.tuples(
        e_strat,
        st.lists(st.integers(min_value=-100, max_value=100), min_size=1, max_size=3),
    ).map(lambda t: f"{t[0]}.is_in([{', '.join(str(x) for x in t[1])}])")
    # Both documented forms: the default is a REGEX match (the alphabet's "."
    # is the only metacharacter it can produce), literal=True is a substring.
    str_contains = st.one_of(
        _str_literals.map(lambda s: f'pl.col("s").str.contains({repr(s)})'),
        _str_literals.map(lambda s: f'pl.col("s").str.contains({repr(s)}, literal=True)'),
    )
    str_in = st.lists(_str_literals, min_size=1, max_size=3).map(
        lambda items: f'pl.col("s").is_in([{", ".join(repr(x) for x in items)}])'
    )
    return st.one_of(
        comparisons,
        null_checks,
        between_checks,
        in_checks,
        str_contains,
        str_in,
    )


def _num_ops(
    e_strat: st.SearchStrategy[str], b_strat: st.SearchStrategy[str]
) -> st.SearchStrategy[str]:
    binary_arith = st.tuples(e_strat, st.sampled_from(["+", "-", "*"]), e_strat).map(
        lambda t: f"({t[0]} {t[1]} {t[2]})"
    )
    div_arith = st.tuples(e_strat, _non_zero_k).map(lambda t: f"({t[0]} / pl.lit({t[1]}))")
    abs_op = e_strat.map(lambda e: f"{e}.abs()")
    round_op = st.tuples(e_strat, st.integers(min_value=0, max_value=3)).map(
        lambda t: f"{t[0]}.round({t[1]})"
    )
    clip_op = st.one_of(
        st.tuples(e_strat, _bounds).map(lambda t: f"{t[0]}.clip({t[1][0]}, {t[1][1]})"),
        st.tuples(e_strat, _bounds).map(
            lambda t: f"{t[0]}.clip(lower_bound={t[1][0]}, upper_bound={t[1][1]})"
        ),
    )
    fill_null_op = st.tuples(e_strat, _num_literals).map(
        lambda t: f"{t[0]}.fill_null({repr(t[1])})"
    )
    sqrt_op = e_strat.map(lambda e: f"{e}.sqrt()")
    log_op = e_strat.map(lambda e: f"{e}.log()")
    when_op = st.tuples(b_strat, e_strat, e_strat).map(
        lambda t: f"pl.when({t[0]}).then({t[1]}).otherwise({t[2]})"
    )
    return st.one_of(
        binary_arith,
        div_arith,
        abs_op,
        round_op,
        clip_op,
        fill_null_op,
        sqrt_op,
        log_op,
        when_op,
    )


_num_0 = _num_leaves
_bool_0 = _bool_exprs(_num_0)

_num_1 = st.one_of(_num_0, _num_ops(_num_0, _bool_0))
_bool_1 = st.one_of(_bool_0, _bool_exprs(_num_1))

_num_2 = st.one_of(_num_1, _num_ops(_num_1, _bool_1))
_bool_2 = st.one_of(_bool_1, _bool_exprs(_num_2))

_num_3 = st.one_of(_num_2, _num_ops(_num_2, _bool_2))
_bool_3 = st.one_of(_bool_2, _bool_exprs(_num_3))

expression_grammar = st.one_of(_num_3, _bool_3, _string_exprs)

_num_or_null = st.none() | _num_literals
_str_or_null = st.none() | _str_literals
row_grammar = st.fixed_dictionaries(
    {
        "x": _num_or_null,
        "y": _num_or_null,
        "s": _str_or_null,
    }
)

# ---------------------------------------------------------------------------
# Test 1: Full parity property
# ---------------------------------------------------------------------------


@pr_budget(300)
@given(expr=expression_grammar, row=row_grammar)
@example(expr='pl.col("x").round(2)', row={"x": 2.675, "y": 0, "s": ""})
@example(expr='pl.col("x").round(0)', row={"x": 0.5, "y": 0, "s": ""})
@example(expr='pl.col("x").round(0)', row={"x": -2.5, "y": 0, "s": ""})
@example(
    expr='pl.col("x").is_between(1, 5, closed="left")',
    row={"x": 5.0, "y": 0, "s": ""},
)
@example(expr='pl.col("s").str.contains("a.c")', row={"x": 0, "y": 0, "s": "abc"})
@example(
    expr='pl.col("s").str.contains("a.c", literal=True)',
    row={"x": 0, "y": 0, "s": "abc"},
)
@example(
    expr='(pl.col("x") + pl.col("y"))',
    row={"x": None, "y": 5, "s": ""},
)
def test_evaluator_agrees_with_polars_on_documented_single_row_forms(expr: str, row: dict) -> None:
    try:
        expected = _polars_value(expr, row)
    except Exception:
        # Outside Polars' supported domain for this form: not a parity claim.
        assume(False)

    actual = _trace_value(expr, row)
    assert values_equivalent(actual, expected), (
        f"Mismatch for {expr} on {row}: trace={actual!r} polars={expected!r}"
    )


# ---------------------------------------------------------------------------
# Test 2: Negative control via naive evaluator
# ---------------------------------------------------------------------------


class _NaiveEvaluator:
    """Test-local naive evaluator reflecting naive Python semantics."""

    def __init__(self, row: dict) -> None:
        self.row = row

    def evaluate(self, node: ast.AST) -> object:
        if isinstance(node, ast.Constant):
            return node.value
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.USub, ast.UAdd)):
            operand = self.evaluate(node.operand)
            if operand is None:
                return None
            return -operand if isinstance(node.op, ast.USub) else operand
        if isinstance(node, ast.Name):
            return self.row.get(node.id)
        if isinstance(node, ast.List):
            return [self.evaluate(elt) for elt in node.elts]
        if isinstance(node, ast.BinOp):
            left = self.evaluate(node.left)
            right = self.evaluate(node.right)
            if left is None or right is None:
                return None
            if isinstance(node.op, ast.Add):
                return left + right
            if isinstance(node.op, ast.Sub):
                return left - right
            if isinstance(node.op, ast.Mult):
                return left * right
            if isinstance(node.op, ast.Div):
                return left / right if right != 0 else None
            return None
        if isinstance(node, ast.Compare):
            left = self.evaluate(node.left)
            right = self.evaluate(node.comparators[0])
            # Naive semantics: comparisons with None return False instead of null
            if left is None or right is None:
                return False
            op = node.ops[0]
            if isinstance(op, ast.Lt):
                return left < right
            if isinstance(op, ast.LtE):
                return left <= right
            if isinstance(op, ast.Gt):
                return left > right
            if isinstance(op, ast.GtE):
                return left >= right
            if isinstance(op, ast.Eq):
                return left == right
            if isinstance(op, ast.NotEq):
                return left != right
            return False
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Attribute):
                attr = node.func.attr
                val = node.func.value
                if isinstance(val, ast.Name) and val.id == "pl":
                    if attr == "col":
                        return self.row.get(node.args[0].value)
                    if attr == "lit":
                        return self.evaluate(node.args[0])
                    if attr == "when":
                        return None
                if attr == "otherwise":
                    then_node = val
                    when_node = then_node.func.value
                    cond = self.evaluate(when_node.args[0])
                    if cond:
                        return self.evaluate(then_node.args[0])
                    return self.evaluate(node.args[0])
                if attr in ("to_lowercase", "to_uppercase"):
                    s_val = self.evaluate(val.value)
                    if s_val is None:
                        return None
                    return s_val.lower() if attr == "to_lowercase" else s_val.upper()
                if attr == "contains":
                    s_val = self.evaluate(val.value)
                    if s_val is None:
                        return None
                    pattern = self.evaluate(node.args[0])
                    # Naive: substring in ignoring literal flag
                    return pattern in s_val
                recv = self.evaluate(val)
                if attr == "round":
                    if recv is None:
                        return None
                    n = self.evaluate(node.args[0]) if node.args else 0
                    # Naive: Python built-in round(v, n)
                    return round(recv, n)
                if attr == "is_between":
                    if recv is None:
                        return False
                    lo = self.evaluate(node.args[0])
                    hi = self.evaluate(node.args[1])
                    if lo is None or hi is None:
                        return False
                    # Naive: ignoring closed, always inclusive
                    return lo <= recv <= hi
                if attr == "abs":
                    return abs(recv) if recv is not None else None
                if attr == "is_null":
                    return recv is None
                if attr == "is_not_null":
                    return recv is not None
                if attr == "fill_null":
                    if recv is not None:
                        return recv
                    return self.evaluate(node.args[0])
                if attr == "sqrt":
                    if recv is not None and recv >= 0:
                        return math.sqrt(recv)
                    return None
                if attr == "log":
                    if recv is not None and recv > 0:
                        return math.log(recv)
                    return None
                if attr == "clip":
                    if recv is None:
                        return None
                    lo = self.evaluate(node.args[0]) if node.args else None
                    hi = self.evaluate(node.args[1]) if len(node.args) > 1 else None
                    for kw in node.keywords:
                        if kw.arg == "lower_bound":
                            lo = self.evaluate(kw.value)
                        elif kw.arg == "upper_bound":
                            hi = self.evaluate(kw.value)
                    if lo is not None and recv < lo:
                        return lo
                    if hi is not None and recv > hi:
                        return hi
                    return recv
                if attr == "is_in":
                    if recv is None:
                        return False
                    items = self.evaluate(node.args[0])
                    return recv in items
            return None
        return None


def _naive_eval(expr_text: str, row: dict) -> object:
    body = ast.parse(expr_text, mode="eval").body
    return _NaiveEvaluator(row).evaluate(body)


def _naive_disagrees_while_trace_agrees(pair: tuple[str, dict]) -> bool:
    expr, row = pair
    try:
        p_val = _polars_value(expr, row)
        n_val = _naive_eval(expr, row)
        t_val = _trace_value(expr, row)
    except Exception:
        return False
    return (not values_equivalent(n_val, p_val)) and values_equivalent(t_val, p_val)


# The four documented divergences the 2026-06-24 audit found, as retained
# examples: each must be caught by the naive evaluator comparison on its own.
_RETAINED_NAIVE_DIVERGENCES = [
    ('pl.col("x").round(2)', {"x": 2.675, "y": 0, "s": ""}),
    ('pl.col("s").str.contains("a.c")', {"x": 0, "y": 0, "s": "abc"}),
    ('pl.col("x").is_between(1, 5, closed="left")', {"x": 5.0, "y": 0, "s": ""}),
    ("(pl.col('x') > 0)", {"x": None, "y": 0, "s": ""}),
]


def test_naive_python_semantics_are_detected() -> None:
    """Negative control: the generated domain separates Polars from naive Python.

    A test-local evaluator with naive Python semantics (decimal ``round``,
    substring ``contains``, always-inclusive ``is_between``, ``False`` for a
    comparison against null) must be caught by the parity property on an
    example drawn from the SAME grammar the property uses, while the production
    evaluator agrees with Polars on that example.
    """
    found_expr, found_row = find(
        st.tuples(expression_grammar, row_grammar),
        _naive_disagrees_while_trace_agrees,
        settings=pr_budget(300),
    )

    naive_val = _naive_eval(found_expr, found_row)
    polars_val = _polars_value(found_expr, found_row)
    trace_val = _trace_value(found_expr, found_row)

    assert not values_equivalent(naive_val, polars_val), (
        f"Naive value should differ from Polars for {found_expr} on {found_row}: "
        f"naive={naive_val!r} polars={polars_val!r}"
    )
    assert values_equivalent(trace_val, polars_val), (
        f"Trace value should match Polars for {found_expr} on {found_row}: "
        f"trace={trace_val!r} polars={polars_val!r}"
    )

    for expr, row in _RETAINED_NAIVE_DIVERGENCES:
        assert _naive_disagrees_while_trace_agrees((expr, row)), (expr, row)


# ---------------------------------------------------------------------------
# Test 3: Unsupported and window forms classification
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "expr_text",
    [
        'pl.col("x").sum().over("y")',
        'pl.col("x").over("y")',
        'pl.col("x").shift(1)',
        'pl.col("x").diff()',
        'pl.col("x").mean()',
    ],
)
def test_receiver_value_window_forms_classified(expr_text: str) -> None:
    row = {"x": 42.0, "y": 1, "s": "abc"}
    actual = _trace_value(expr_text, row)
    assert actual == 42.0


@pytest.mark.parametrize(
    "expr_text",
    [
        'pl.col("x").cum_sum()',
        'pl.col("x").rolling_mean(2)',
        'pl.col("x").str.slice(1)',
    ],
)
def test_unsupported_forms_return_none(expr_text: str) -> None:
    row = {"x": 42.0, "y": 1, "s": "abc"}
    actual = _trace_value(expr_text, row)
    assert actual is None


def test_window_semantics_diverge_from_single_row_approximation() -> None:
    two_row_df = pl.DataFrame({"x": [10.0, 20.0], "y": [1, 1]})
    polars_window = two_row_df.select(pl.col("x").sum().over("y"))["x"].to_list()
    assert polars_window == [30.0, 30.0]
    assert polars_window != [10.0, 20.0]
