"""Script codegen: generate standalone TrainingJob Python scripts."""

from __future__ import annotations

from typing import Any

from haute.modelling._train_config import build_training_job_kwargs


def _training_job_uses_tweedie_variance_power(kwargs: dict[str, Any]) -> bool:
    """Return whether ``TrainingJob.variance_power`` affects this export."""
    if kwargs["loss_function"] == "Tweedie":
        return True

    if str(kwargs["algorithm"]).lower() == "glm":
        family = kwargs["params"].get("family")
        return isinstance(family, str) and family.lower() == "tweedie"

    return False


def generate_training_script(config: dict[str, Any], data_path: str) -> str:
    """Generate a self-contained Python training script.

    The generated script uses ``from haute.modelling import TrainingJob``
    and can be run standalone, used as a Databricks Job, or modified for
    experimentation.

    The TrainingJob kwargs are built by the same config→kwargs builder live
    training uses (``haute.modelling._train_config``), so the script trains
    the same model as the in-app "Train" button. In particular, GLM config
    (terms/family/link/regularization/…) lives at the config top level and is
    merged into ``params`` — an exported GLM script without that merge would
    silently train a Gaussian all-features model instead.

    Parameters
    ----------
    config : dict
        Modelling node configuration containing algorithm, target, weight,
        exclude, params, split, metrics, mlflow_experiment, model_name,
        loss_function, variance_power, offset, monotone_constraints,
        feature_weights, etc.
    data_path : str
        Path to the training data file (e.g. "output/frequency.parquet").

    Returns
    -------
    str
        Complete Python script as a string.
    """
    kwargs = build_training_job_kwargs(config, data=data_path)

    parts: list[str] = [
        '"""Training script generated by Haute."""',
        "",
        "from haute.modelling import TrainingJob",
        "",
        "",
        "job = TrainingJob(",
        f"    name={kwargs['name']!r},",
        f"    data={kwargs['data']!r},",
        f"    target={kwargs['target']!r},",
    ]

    # Optional kwargs are rendered only when set: TrainingJob's defaults for
    # the omitted values are identical to what live training passes (None/[]),
    # so skipping them keeps the script readable without changing the model.
    if kwargs["weight"]:
        parts.append(f"    weight={kwargs['weight']!r},")
    if kwargs["exclude"]:
        parts.append(f"    exclude={kwargs['exclude']!r},")
    if kwargs["feature_columns"]:
        parts.append(f"    feature_columns={kwargs['feature_columns']!r},")
    if kwargs["fold_column"]:
        parts.append(f"    fold_column={kwargs['fold_column']!r},")
    if kwargs["id_columns"]:
        parts.append(f"    id_columns={kwargs['id_columns']!r},")

    parts.append(f"    algorithm={kwargs['algorithm']!r},")
    parts.append(f"    task={kwargs['task']!r},")

    if kwargs["params"]:
        parts.append(f"    params={kwargs['params']!r},")

    parts.append(f"    split={kwargs['split']!r},")
    parts.append(f"    metrics={kwargs['metrics']!r},")

    if kwargs["loss_function"]:
        parts.append(f"    loss_function={kwargs['loss_function']!r},")
    # Tweedie deviance needs the same variance power as live training.
    if kwargs["variance_power"] is not None and _training_job_uses_tweedie_variance_power(kwargs):
        parts.append(f"    variance_power={kwargs['variance_power']!r},")
    if kwargs["offset"]:
        parts.append(f"    offset={kwargs['offset']!r},")
    if kwargs["monotone_constraints"]:
        parts.append(f"    monotone_constraints={kwargs['monotone_constraints']!r},")
    if kwargs["feature_weights"]:
        parts.append(f"    feature_weights={kwargs['feature_weights']!r},")
    if kwargs["categorical_levels"]:
        parts.append(f"    categorical_levels={kwargs['categorical_levels']!r},")

    if kwargs["mlflow_experiment"]:
        parts.append(f"    mlflow_experiment={kwargs['mlflow_experiment']!r},")
    if kwargs["model_name"]:
        parts.append(f"    model_name={kwargs['model_name']!r},")

    parts.append(f"    output_dir={kwargs['output_dir']!r},")
    parts.append(")")
    parts.append("")
    parts.append("")
    parts.append('if __name__ == "__main__":')
    parts.append("    result = job.run()")
    parts.append('    print(f"Model saved to: {result.model_path}")')
    parts.append("    for name, value in result.metrics.items():")
    parts.append('        print(f"  {name}: {value:.4f}")')
    parts.append("")

    return "\n".join(parts)
