import type { ExecutionMetrics } from "../api/types"

export function makeExecutionMetricsFixture(overrides: Partial<ExecutionMetrics> = {}): ExecutionMetrics {
  return {
    schema_version: 1,
    operation: "pipeline_preview",
    profile: "preview_eager",
    job_id: "job-1",
    status: "running",
    terminal_reason: null,
    stage_count: 1,
    retained_stage_count: 1,
    truncated_stage_count: 0,
    stages_truncated: false,
    total_elapsed_ms: 12.5,
    node_elapsed_ms: { score: 12.5 },
    stage_elapsed_ms: { collect: 12.5 },
    rss_start_bytes: 1_000,
    rss_end_bytes: 1_800,
    rss_delta_bytes: 800,
    rss_peak_bytes: 1_800,
    max_rss_bytes: 1_800,
    n_collects: 1,
    n_checkpoints: 2,
    memory_pressure_event_count: 1,
    retained_memory_pressure_event_count: 1,
    truncated_memory_pressure_event_count: 0,
    memory_pressure_events_truncated: false,
    memory_limit_bytes: 2_000,
    memory_baseline_bytes: 1_000,
    rss_limit_bytes: 3_000,
    streamability: null,
    streamability_evidence: { state: "unavailable", total_count: null, items: [] },
    column_widths: { state: "available", total_count: 0, items: [] },
    bytes_read: null,
    bytes_written: null,
    estimated_bytes: null,
    observed_peak_rss_bytes: null,
    checkpoint_count: 0,
    chunk_count: 0,
    execution_strategy: null,
    admission: {
      admitted: true,
      operation: "pipeline_preview",
      profile: "preview_eager",
      memory_limit_bytes: 2_000,
      rss_at_admission_bytes: 1_000,
      rss_limit_bytes: 3_000,
      process_rss_limit_bytes: null,
      headroom_bytes: 2_000,
      config_key: "HAUTE_PREVIEW_MEMORY_LIMIT_MB",
      budget_policy: "adaptive_local",
      available_ram_bytes: 8_000,
      os_reserve_bytes: 2_000,
      reason: "within_memory_budget",
    },
    stages: [
      {
        schema_version: 1,
        name: "collect",
        operation: "pipeline_preview",
        profile: "preview_eager",
        elapsed_ms: 12.5,
        node_id: "score",
        job_id: "job-1",
        rss_start_bytes: 1_000,
        rss_end_bytes: 1_800,
        rss_delta_bytes: 800,
        rss_peak_bytes: 1_800,
        rows_in: 10,
        rows_out: 2,
        bytes_read: 512,
        bytes_written: 128,
        columns_scanned: 4,
        n_collects: 1,
        n_checkpoints: 2,
      },
    ],
    memory_pressure_events: [
      {
        schema_version: 1,
        event: "memory_pressure",
        operation: "pipeline_preview",
        profile: "preview_eager",
        job_id: "job-1",
        node_id: "score",
        stage: "collect",
        label: "after_collect",
        threshold_ratio: 0.75,
        threshold_percent: 75,
        rss_bytes: 1_750,
        rss_limit_bytes: 3_000,
        headroom_bytes: 2_000,
        headroom_used_bytes: 1_500,
        rss_peak_bytes: 1_800,
        memory_limit_bytes: 2_000,
        memory_baseline_bytes: 1_000,
        baseline_rss_bytes: 1_000,
        budget_policy: "adaptive_local",
        config_key: "HAUTE_PREVIEW_MEMORY_LIMIT_MB",
        available_ram_bytes: 8_000,
        os_reserve_bytes: 2_000,
        pressure_ratio: 0.75,
      },
    ],
    ...overrides,
  }
}
