"""Atomic working/ledger branch-pair saves, milestones, and forks."""

from __future__ import annotations

from pathlib import Path

# The command core is the sole process boundary.  Its helpers are imported
# explicitly into this domain's namespace so extracted functions retain their
# original signatures and semantics without a facade dependency.
from haute._git_core import (
    GitDomainError,
    GitError,
    GitGuardrailError,
    GitMilestoneForkError,
    GitTransactionError,
    _assert_eligible_working,
    _assert_git_repo,
    _canonical_remote,
    _commit_parents,
    _generate_commit_message,
    _get_current_branch,
    _is_ancestor,
    _is_valid_full_ref_name,
    _ledger_or_branch_sha,
    _merge_base,
    _remote_names,
    _rev_parse,
    _run_git,
    _run_git_ok,
    _serialized_mutation,
    _tree_of,
    _validate_ref_name,
    divergence_state,
    ledger_name,
)
from haute._git_setup import resolve_ledger, set_working_branch
from haute._logging import get_logger
from haute.schemas import GitCommitResponse, GitCreateWorkingBranchResponse, GitMilestoneFork

logger = get_logger(component="git")

__all__ = [
    "commit_save",
    "check_invariants",
    "merge_to_working",
    "create_working_branch",
    "commit_milestone",
]


@_serialized_mutation
def commit_save(
    paths: list[str], working: str, cwd: Path | None = None, message: str | None = None
) -> str | None:
    """Record one save as one commit on the ledger of *working*.

    Pathspec-scoped: only *paths* enter the commit, regardless of any content
    the user may have staged in the meantime. Returns the new commit SHA, or
    None when none of *paths* changed (idempotent saves produce no empty
    commits).
    """
    if not paths:
        return None

    ledger = resolve_ledger(working, cwd=cwd)

    ok, status = _run_git_ok("status", "--porcelain", "--", *paths, cwd=cwd)
    if not ok or not status.strip():
        return None

    changed = [line[3:] for line in status.strip().splitlines()]
    msg = message if message is not None else _generate_commit_message(changed)

    # New files must be known to git before a pathspec'd commit can include
    # them; the explicit-path add also stages deletions of tracked paths.
    _run_git("add", "--", *paths, cwd=cwd)
    # A stale index entry can make porcelain report ``MM`` even when the
    # working-tree content already matches HEAD. The add above reconciles that
    # entry; if no net path change remains, there is nothing to commit.
    clean, _ = _run_git_ok("diff", "--cached", "--quiet", "HEAD", "--", *paths, cwd=cwd)
    if clean:
        return None
    # `git commit -- <paths>` commits the working-tree state of exactly those
    # paths, bypassing unrelated index content the user may have pre-staged.
    _run_git("commit", "-m", msg, "--", *paths, cwd=cwd)

    sha = _run_git("rev-parse", "HEAD", cwd=cwd).strip()
    logger.info("save_committed", ledger=ledger, sha=sha, files=len(changed))
    return sha


def _residual_tracked_changes(cwd: Path | None = None) -> list[str]:
    """Return tracked paths whose index or working content differs from HEAD.

    Milestone commits represent the whole tracked project state, not only the
    files last generated by the canvas save. Untracked/staged-new files are
    deliberately excluded so an unrelated local file cannot silently enter
    history. Both comparisons are needed: the HEAD comparison finds real net
    changes, while the index comparison also finds stale ``MM`` entries whose
    working content has returned to HEAD and merely need reconciliation.
    """

    def parse_name_status(raw: str) -> list[str]:
        tokens = raw.split("\0")
        paths: list[str] = []
        i = 0
        while i < len(tokens) and tokens[i]:
            status = tokens[i]
            i += 1
            code = status[0]
            if code in ("R", "C"):
                if i + 1 >= len(tokens):
                    raise GitError("Malformed git name-status output.")
                old_path, new_path = tokens[i], tokens[i + 1]
                i += 2
                paths.extend((old_path, new_path))
            else:
                if i >= len(tokens):
                    raise GitError("Malformed git name-status output.")
                path = tokens[i]
                i += 1
                # A means newly staged/untracked. Save & commit captures only
                # files that were already tracked by the project.
                if code in ("M", "D", "T"):
                    paths.append(path)
        return paths

    net = _run_git("diff", "--name-status", "-z", "-M", "HEAD", "--", cwd=cwd)
    staged = _run_git("diff", "--cached", "--name-status", "-z", "-M", "HEAD", "--", cwd=cwd)
    return list(dict.fromkeys(parse_name_status(net) + parse_name_status(staged)))


def check_invariants(working: str, cwd: Path | None = None) -> list[str]:
    """Cheap plumbing checks of the branch-pair healthy-state invariant.

    Returns a list of human-readable violations (empty == healthy). Used at
    open and before every milestone merge.
    """
    _assert_git_repo(cwd)
    violations: list[str] = []

    working_tip = _rev_parse(working, cwd=cwd)
    if working_tip is None:
        return [f"working branch '{working}' does not exist"]

    ledger = ledger_name(working)
    ledger_tip = _rev_parse(ledger, cwd=cwd)
    if ledger_tip is None:
        return []  # pre-spawn: nothing to check

    base = _merge_base(working_tip, ledger_tip, cwd=cwd)
    if base is None:
        violations.append(f"'{working}' and '{ledger}' share no history")
        return violations

    if not _is_ancestor(base, ledger_tip, cwd=cwd):
        violations.append(f"merge-base of '{working}' and '{ledger}' is not on the ledger")

    if _tree_of(working_tip, cwd=cwd) != _tree_of(base, cwd=cwd):
        violations.append(
            f"'{working}' tip tree differs from its last-merged ledger commit — "
            "the working branch was advanced outside haute"
        )

    return violations


@_serialized_mutation
def merge_to_working(
    working: str,
    message: str,
    tag_label: str | None = None,
    cwd: Path | None = None,
) -> str:
    """Milestone merge: ledger → working, always a real merge commit.

    Produced with plumbing (``commit-tree`` + ``update-ref``) — no checkout,
    no index, and by construction never a fast-forward. The user-supplied
    *message* rides the merge commit itself. Returns the milestone SHA.
    """
    _assert_git_repo(cwd)
    _validate_ref_name(working)
    _assert_eligible_working(working)

    ledger = ledger_name(working)
    working_tip = _rev_parse(working, cwd=cwd)
    ledger_tip = _rev_parse(ledger, cwd=cwd)
    if working_tip is None:
        raise GitDomainError(f"Working branch '{working}' does not exist.")
    if ledger_tip is None:
        raise GitDomainError(f"'{working}' has no save ledger yet — nothing to commit.")

    if not message.strip():
        raise GitDomainError("A commit message is required.")
    # Reject C0 control characters (except tab/newline/CR, which are valid in a
    # multi-line message). A stray record-separator etc. would otherwise corrupt
    # the ledger-history parser, which delimits commits with \x1e.
    if any((ord(c) < 0x20 and c not in "\t\n\r") or ord(c) == 0x7F for c in message):
        raise GitDomainError("Commit message must not contain control characters.")

    tag_ref: str | None = None
    if tag_label is not None:
        _validate_ref_name(tag_label)
        tag_ref = f"version/{tag_label}"
        if not _is_valid_full_ref_name(f"refs/tags/{tag_ref}"):
            raise GitDomainError(f"Version label {tag_label!r} is not a valid Git tag name.")
        ok, _ = _run_git_ok("rev-parse", "--verify", "--quiet", f"refs/tags/{tag_ref}", cwd=cwd)
        if ok:
            raise GitDomainError(f"Version label '{tag_label}' already exists.")

    violations = check_invariants(working, cwd=cwd)
    if violations:
        raise GitDomainError(
            "Cannot commit to the working branch: " + "; ".join(violations) + ". "
            "Use the branch manager to start a fresh branch from your current state."
        )

    base = _merge_base(working_tip, ledger_tip, cwd=cwd)
    if base == ledger_tip:
        raise GitDomainError("No new saves to commit — the working branch is up to date.")

    tree = _tree_of(ledger_tip, cwd=cwd)
    sha = _run_git(
        "commit-tree", tree, "-p", working_tip, "-p", ledger_tip, "-m", message, cwd=cwd
    ).strip()
    if tag_ref is None:
        _run_git("update-ref", f"refs/heads/{working}", sha, working_tip, cwd=cwd)
    else:
        # Build the annotated tag object without publishing its ref, then update
        # the branch CAS and create the label in one ref transaction. If either
        # precondition loses a race, Git applies neither update.
        tagger = _run_git("var", "GIT_COMMITTER_IDENT", cwd=cwd)
        tag_object = _run_git(
            "hash-object",
            "--literally",
            "-t",
            "tag",
            "-w",
            "--stdin",
            cwd=cwd,
            input_text=(
                f"object {sha}\ntype commit\ntag {tag_ref}\ntagger {tagger}\n\n{tag_label}\n"
            ),
        )
        _run_git(
            "update-ref",
            "--stdin",
            cwd=cwd,
            input_text=(
                f"update refs/heads/{working} {sha} {working_tip}\n"
                f"create refs/tags/{tag_ref} {tag_object}\n"
            ),
        )

    logger.info("milestone_merged", working=working, sha=sha, tag=tag_label or "", ledger=ledger)
    return sha


def _on_first_parent(working: str, commit: str, cwd: Path | None = None) -> bool:
    """Whether *commit* sits on *working*'s first-parent (milestone) chain."""
    ok, raw = _run_git_ok("rev-list", "--first-parent", working, cwd=cwd)
    return ok and commit in raw.split()


def _commits_in_range(start: str, end: str, cwd: Path | None = None) -> list[str]:
    """SHAs in ``start..end``, oldest-first (ready to replay onto a new base)."""
    ok, raw = _run_git_ok("rev-list", "--reverse", f"{start}..{end}", cwd=cwd)
    return raw.split() if ok and raw.strip() else []


def _crystallize_milestone(working_tip: str, save: str, name: str, cwd: Path | None = None) -> str:
    """An anchoring milestone for a new branch forked at a pending *save*: a real
    merge commit (parents = latest milestone + the save) carrying the save's
    tree, so the new branch opens at a clean milestone capturing that state."""
    tree = _tree_of(save, cwd=cwd)
    msg = f"Start {name} from save {save[:8]}"
    return _run_git("commit-tree", tree, "-p", working_tip, "-p", save, "-m", msg, cwd=cwd)


def _replay_onto(base: str, commits: list[str], cwd: Path | None = None) -> str:
    """Replay each commit (its tree + message) onto *base* via plumbing, linear,
    returning the new tip. Trees apply cleanly because the commits already formed
    a linear chain whose root has *base*'s tree. Author + committer identity and
    dates are preserved (relocated saves keep their provenance + timeline, S38).
    Empty *commits* returns base."""
    tip = base
    for c in commits:
        if len(_commit_parents(c, cwd=cwd)) != 1:
            raise GitDomainError(
                "Create & Move cannot relocate history containing a merge commit. "
                "Create a parallel branch instead so the merge topology is preserved."
            )
        tree = _tree_of(c, cwd=cwd)
        msg = _run_git("log", "-1", "--format=%B", c, cwd=cwd)
        # \x1f (unit separator) can't appear in identity/date fields.
        an, ae, ad, cn, ce, cd = _run_git(
            "log", "-1", "--format=%an%x1f%ae%x1f%aI%x1f%cn%x1f%ce%x1f%cI", c, cwd=cwd
        ).split("\x1f")
        env = {
            "GIT_AUTHOR_NAME": an,
            "GIT_AUTHOR_EMAIL": ae,
            "GIT_AUTHOR_DATE": ad,
            "GIT_COMMITTER_NAME": cn,
            "GIT_COMMITTER_EMAIL": ce,
            "GIT_COMMITTER_DATE": cd,
        }
        tip = _run_git("commit-tree", tree, "-p", tip, "-m", msg, cwd=cwd, env=env)
    return tip


def _rollback_fork(name: str, ledger: str, ledger_tip: str, cwd: Path | None = None) -> bool:
    """Undo a partially-applied fork and report whether every step succeeded."""
    succeeded = True
    new_ledger = ledger_name(name)
    if _get_current_branch(cwd) == new_ledger:
        # The spawning ledger isn't checked out → safe to restore it, then move
        # HEAD back so the new ledger can be deleted.
        ok, _ = _run_git_ok("branch", "-f", ledger, ledger_tip, cwd=cwd)
        succeeded &= ok
        ok, _ = _run_git_ok("checkout", ledger, cwd=cwd)
        succeeded &= ok
    if _rev_parse(new_ledger, cwd=cwd) is not None:
        ok, _ = _run_git_ok("branch", "-D", new_ledger, cwd=cwd)
        succeeded &= ok
    if _rev_parse(name, cwd=cwd) is not None:
        ok, _ = _run_git_ok("branch", "-D", name, cwd=cwd)
        succeeded &= ok
    return succeeded


@_serialized_mutation
def create_working_branch(
    name: str,
    project_root: Path,
    at: str | None = None,
    move: bool = False,
    cwd: Path | None = None,
) -> GitCreateWorkingBranchResponse:
    """Create a new working branch as a fork of the current one (P5d/S38).

    Fork point: ``at=None`` → the current branch's latest milestone; ``at=<sha>``
    → that milestone, or a pending save (crystallized into an anchoring
    milestone). ``move=False`` (default) spins off a parallel line and leaves the
    current branch and your in-progress work untouched — you stay put.
    ``move=True`` relocates the work after the fork point (unmilestoned saves +
    uncommitted edits) onto the new branch, rewinds the current branch's ledger
    to the fork point, and switches you over. Move is valid only at the latest
    milestone or a pending save.
    """
    from haute._git_state import read_working_branch, write_working_branch

    _assert_git_repo(cwd)
    _validate_ref_name(name)
    _assert_eligible_working(name)

    current = read_working_branch(project_root)
    if current is None:
        # No working branch yet — an adopt-create off real HEAD; no fork model.
        if at is not None or move:
            raise GitDomainError("No working branch to fork from yet.")
        res = set_working_branch(name, project_root, create=True, cwd=cwd)
        return GitCreateWorkingBranchResponse(
            working_branch=name,
            moved=False,
            switched=True,
            last_save_sha=res.last_save_sha,
        )

    if _rev_parse(name, cwd=cwd) is not None:
        raise GitDomainError(f"Branch '{name}' already exists.")
    if _rev_parse(ledger_name(name), cwd=cwd) is not None:
        raise GitDomainError(f"A branch named '{ledger_name(name)}' already exists.")

    working_tip = _rev_parse(current, cwd=cwd)
    if working_tip is None:
        raise GitDomainError(f"Working branch '{current}' does not exist.")
    ledger = ledger_name(current)
    ledger_tip = _rev_parse(ledger, cwd=cwd) or working_tip

    if at is not None:
        _validate_ref_name(at)  # same guard every other user-supplied ref gets
    point = working_tip if at is None else _rev_parse(at, cwd=cwd)
    if point is None:
        raise GitDomainError(f"Commit '{at}' does not exist.")

    is_milestone = _on_first_parent(current, point, cwd=cwd)
    is_pending = (
        not is_milestone
        and _is_ancestor(point, ledger_tip, cwd=cwd)
        and not _is_ancestor(point, working_tip, cwd=cwd)
    )
    if not is_milestone and not is_pending:
        raise GitDomainError(
            "You can only branch from a milestone or a pending save on the current branch."
        )

    base = point if is_milestone else _crystallize_milestone(working_tip, point, name, cwd=cwd)

    if not move:
        # Parallel fork: two fresh refs at the base; current and HEAD untouched.
        _run_git("branch", name, base, cwd=cwd)
        try:
            _run_git("branch", ledger_name(name), base, cwd=cwd)
        except GitError:
            _run_git_ok("branch", "-D", name, cwd=cwd)  # don't leak a lone ref
            raise
        logger.info("working_branch_forked", name=name, at=point[:8], moved=False)
        return GitCreateWorkingBranchResponse(
            working_branch=name,
            moved=False,
            switched=False,
            last_save_sha=_ledger_or_branch_sha(name, cwd=cwd),
        )

    # Move: only at the latest milestone or a pending save.
    if is_milestone and point != working_tip:
        raise GitDomainError(
            "Create & Move is only available at the latest milestone or a "
            "pending save — older milestones can only spin off a parallel line."
        )
    # M5 safety: move-mode rewinds the spawning branch's ledger to the fork
    # point (the ``branch -f`` below). If that ledger is already published, the
    # rewind drops commits the remote still has, leaving the source pair
    # un-pushable (non-fast-forward) — and S33 forbids the force-push that would
    # fix it. Refuse and steer to a parallel fork, which rewinds nothing. Only
    # refuse when the rewind genuinely orphans published commits (the remote
    # ledger is not an ancestor of the fork point); a tip-fork stays frictionless.
    for remote in _remote_names(cwd=cwd):
        remote_ledger = _rev_parse(f"refs/remotes/{remote}/{ledger}", cwd=cwd)
        if remote_ledger is not None and not _is_ancestor(remote_ledger, point, cwd=cwd):
            raise GitGuardrailError(
                "This branch's save history is published, and moving from here "
                "would rewind it past the shared copy. Spin off a parallel line "
                "instead — it leaves this branch untouched."
            )
    # The new ledger carries the saves after the fork point. At the latest
    # milestone the pending chain already sits on the base, so reuse it; at a
    # pending save, replay the later saves onto the crystallized milestone.
    if is_milestone:
        new_ledger_tip = ledger_tip
    else:
        new_ledger_tip = _replay_onto(base, _commits_in_range(point, ledger_tip, cwd=cwd), cwd=cwd)

    # The mutations below are not individually atomic; on any failure roll the
    # whole fork back so the user isn't wedged behind the "already exists" guard
    # with work duplicated across two lineages (S38).
    try:
        _run_git("branch", name, base, cwd=cwd)
        _run_git("branch", ledger_name(name), new_ledger_tip, cwd=cwd)
        # Switch onto the new ledger. The new ledger tip shares the old HEAD's
        # tree, so uncommitted edits carry across the checkout untouched.
        _run_git("checkout", ledger_name(name), cwd=cwd)
        # Rewind the spawning branch's ledger to the fork point (its later work
        # has been relocated; the commits stay reachable via the new ledger).
        _run_git("branch", "-f", ledger, point, cwd=cwd)
        write_working_branch(project_root, name)
    except Exception as exc:
        refs_restored = _rollback_fork(name, ledger, ledger_tip, cwd=cwd)
        try:
            write_working_branch(project_root, current)
            state_restored = True
        except OSError:
            state_restored = False
        if not refs_restored or not state_restored:
            raise GitTransactionError(
                "Creating and moving to the branch failed and automatic rollback was "
                "incomplete. Inspect the repository before retrying."
            ) from exc
        raise
    logger.info("working_branch_forked", name=name, at=point[:8], moved=True)
    return GitCreateWorkingBranchResponse(
        working_branch=name,
        moved=True,
        switched=True,
        last_save_sha=_ledger_or_branch_sha(name, cwd=cwd),
    )


@_serialized_mutation
def commit_milestone(
    message: str,
    project_root: Path,
    version_label: str | None = None,
    cwd: Path | None = None,
    allow_fork: bool = False,
) -> GitCommitResponse:
    """Promote the ledger's accumulated saves to a milestone on the working
    branch (a real `--no-ff`-shaped merge commit via plumbing), with the
    user's *message* and an optional version-label tag (S7/S18).

    Fork-gate (U4/D4): if the working branch is behind/diverged from its canonical
    remote on locally-known refs, a milestone would branch off the shared copy —
    refuse with :class:`GitMilestoneForkError` so the UI can warn, unless
    *allow_fork* is the user's deliberate override. The check is local-only (no
    fetch): the milestone stays instant and a local-only/offline user is never
    blocked (no remote, or an untracked/unknown leg, degrades open)."""
    from haute._git_state import read_working_branch

    _assert_git_repo(cwd)
    working = read_working_branch(project_root)
    if working is None:
        raise GitDomainError("No working branch is set for this project.")

    if not allow_fork:
        leg = divergence_state(working, cwd=cwd)
        if leg is not None and leg.status in ("behind", "diverged"):
            remote = _canonical_remote(cwd) or "the remote"
            behind = leg.behind or 0
            message_text = (
                f"Saving a milestone now will fork '{remote}' — it has {behind} newer "
                f"milestone{'' if behind == 1 else 's'} on this branch that you don't "
                "have yet, so your version would branch off the shared one instead of "
                "building on it. Your work is safe — commit anyway to create a fork, "
                "or catch up first."
            )
            raise GitMilestoneForkError(
                GitMilestoneFork(remote=remote, working=leg, message=message_text)
            )

    # The canvas save immediately preceding this action captures Haute-owned
    # generated files. A project can also have changes to already-tracked files
    # made by dependency tooling or a code editor (uv.lock is a common example).
    # Fold those into the ledger before creating the milestone so an explicit
    # "Save & commit" leaves the tracked project clean. Newly-added/untracked
    # files remain untouched and cannot ride into history implicitly.
    residual = _residual_tracked_changes(cwd)
    if residual:
        commit_save(residual, working, cwd=cwd, message="Updated tracked project files")

    sha = merge_to_working(working, message, tag_label=version_label, cwd=cwd)
    logger.info("milestone_committed", working=working, sha=sha, tag=version_label or "")
    return GitCommitResponse(
        sha=sha,
        short_sha=sha[:8],
        working_branch=working,
        version_label=version_label,
    )
