"""Loader for the committed polars I/O argument schema.

``_polars_io_arguments.json`` (package data, regenerated by
``scripts/extract_polars_io.py``) records the full polars I/O callable
surface — names, argument kinds/positions/annotations/defaults, and
docstring-documentation flags — for the polars version haute pins.

It serves two purposes:

1. **Interface contract.** ``tests/test_polars_io_interface_contracts.py``
   re-extracts the schema from the installed polars and fails on any
   argument-level drift, so an in-cap polars release that changes the I/O
   surface is caught by CI (including the scheduled unlocked-resolve lane)
   rather than by a user.
2. **Config validation source.** The data-input/data-output node machinery
   validates node-config argument names against this schema instead of
   hand-maintaining per-function argument lists.

The JSON is loaded lazily and cached; importing this module does no I/O.
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib.resources import files
from typing import Any

_SCHEMA_RESOURCE = "_polars_io_arguments.json"


@lru_cache(maxsize=1)
def load_io_schema() -> dict[str, Any]:
    """Load the committed polars I/O argument schema (cached)."""
    raw = files("haute").joinpath(_SCHEMA_RESOURCE).read_text(encoding="utf-8")
    schema: dict[str, Any] = json.loads(raw)
    return schema


@lru_cache(maxsize=1)
def io_functions_by_key() -> dict[str, dict[str, Any]]:
    """Index the schema's functions by ``owner.name`` (e.g. ``polars.read_csv``)."""
    return {f"{fn['owner']}.{fn['name']}": fn for fn in load_io_schema()["functions"]}


def io_function(owner: str, name: str) -> dict[str, Any]:
    """Return one function record; raise ``KeyError`` with the known keys on a miss."""
    key = f"{owner}.{name}"
    functions = io_functions_by_key()
    if key not in functions:
        raise KeyError(
            f"Unknown polars I/O callable {key!r}; known keys include "
            f"{sorted(functions)[:5]} … (see haute/_polars_io_arguments.json)"
        )
    return functions[key]


def argument_names(owner: str, name: str) -> tuple[str, ...]:
    """Argument names of one I/O callable, in signature order."""
    return tuple(arg["name"] for arg in io_function(owner, name)["arguments"])
