// ADVERSARIAL DIFFERENTIAL PARITY TEST (verifier-authored, throwaway).
// Fixture sanitizeParity.fixture.json is generated by the REAL backend
// _sanitize_func_name (src/haute/_graph_utils.py) over 410 generated cases
// spanning keyword / space / hyphen / non-ASCII / control / digit / idempotency
// categories. Each pair is [input, pythonOutput]; we assert the TS sanitizeName
// produces byte-identical output. Any divergence fails here with the input shown.
import { describe, it, expect } from "vitest"
import { sanitizeName } from "../sanitizeName"
import cases from "./sanitizeParity.fixture.json"

describe("sanitizeName <-> backend _sanitize_func_name differential parity", () => {
  it.each(cases as [string, string][])(
    "matches backend for %j",
    (input, expected) => {
      expect(sanitizeName(input)).toBe(expected)
    },
  )
})
