import { describe, expect, it } from "vitest"
import type { Connection, Node } from "@xyflow/react"
import type { PipelineEdge, SubmodelDefinition, SubmodelPortData } from "../../types/node"
import { makeNode } from "../../test-utils/factories"
import { buildSubmodelViewGraph } from "../submodelViewGraph"
import { applySubmodelBoundaryConnection, removeSubmodelBoundaryEdges, type SubmodelBoundaryEditState } from "../submodelBoundaryEditing"
function state(bound = false): SubmodelBoundaryEditState { const children = [makeNode("prepare"), makeNode("score")]; const definition: SubmodelDefinition = { definitionId: "definition_pricing", file: "modules/pricing.py", graph: { nodes: children, edges: [] }, inputPorts: [{ portId: "policy", label: "Policy", targets: [{ nodeId: "prepare", handleId: null }] }], outputPorts: [{ portId: "premium", label: "Premium", source: { nodeId: "score", handleId: "result" } }] }; const parentNodes = [makeNode("instance_primary", "submodel", { data: { label: "Pricing", nodeType: "submodel", config: { definitionId: definition.definitionId, alias: "pricing" } } }), makeNode("instance_secondary", "submodel", { data: { label: "Pricing 2", nodeType: "submodel", config: { definitionId: definition.definitionId, alias: "pricing_2" } } }), makeNode("consumer")]; const parentEdges: PipelineEdge[] = bound ? [{ id: "consumer", source: "instance_primary", sourceHandle: "out__premium", target: "consumer" }] : []; const view = buildSubmodelViewGraph({ submodelName: "pricing", instanceId: "instance_primary", definition, childNodes: children, childEdges: [], parentNodes, parentEdges }); return { submodelName: "pricing", instanceId: "instance_primary", definitionId: definition.definitionId, viewNodes: view.nodes, viewEdges: view.edges as PipelineEdge[], parentNodes, parentEdges, submodels: { [definition.definitionId]: definition } } }
const boundary = (nodes: Node[], direction: "input" | "output") => nodes.find((node) => node.type === "submodelPort" && (node.data as SubmodelPortData).portDirection === direction)!
describe("submodelBoundaryEditing", () => {
  it("adds a target to a canonical input port without changing occurrences", () => { const current = state(); const input = boundary(current.viewNodes, "input"); const result = applySubmodelBoundaryConnection(current, { source: input.id, sourceHandle: "policy", target: "score", targetHandle: "joined" } as Connection); expect(result?.submodels.definition_pricing).toMatchObject({ inputPorts: [{ portId: "policy", targets: [{ nodeId: "prepare", handleId: null }, { nodeId: "score", handleId: "joined" }] }] }); expect(result?.parentNodes.map((node) => node.data.config)).toEqual(current.parentNodes.map((node) => node.data.config)) })
  it("blocks deletion of a used public output", () => { const current = state(true); const output = boundary(current.viewNodes, "output"); const declaration = current.viewEdges.find((edge) => edge.target === output.id)!; expect(() => removeSubmodelBoundaryEdges(current, [declaration.id])).toThrow(/Pricing.*Premium/s) })
  it("removes an unbound public output from the shared definition", () => { const current = state(); const output = boundary(current.viewNodes, "output"); const declaration = current.viewEdges.find((edge) => edge.target === output.id)!; expect(removeSubmodelBoundaryEdges(current, [declaration.id])?.submodels.definition_pricing).toMatchObject({ outputPorts: [] }) })
})