"""``haute train`` command.

Split into:

* :class:`TrainConfig` — the typed bag of CLI inputs.
* :func:`handle_train` — the pure function that does the work.
* :func:`train` — the thin ``@click.command`` entry point.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

import click

from haute._io import read_user_text


@dataclass
class TrainConfig:
    """Parsed inputs for the ``haute train`` command."""

    training_script: Path


_PROGRESS_BAR_WIDTH = 30


def _progress(msg: str, frac: float) -> None:
    """Render a one-line progress bar and flush stdout immediately.

    Exposed at module scope so the train command can pass it to
    ``job.run(progress=_progress)`` and so it can be unit-tested.

    The explicit ``sys.stdout.flush()`` is load-bearing — ``click.echo``
    with ``nl=False`` leaves the line buffered on many terminals so the
    bar appears to hang between updates.  Flushing after every write
    guarantees each intermediate update reaches the user.

    We deliberately use :func:`click.echo` (not a raw ``sys.stdout.write``)
    so this command follows the CLI logging convention documented in
    :mod:`haute._logging` — every CLI-user-facing write goes through
    Click, which gives us ANSI handling + ``err=`` routing consistent
    with every other ``haute`` command.
    """
    bar = "=" * int(frac * _PROGRESS_BAR_WIDTH)
    click.echo(f"\r  [{bar:<{_PROGRESS_BAR_WIDTH}}] {frac:.0%} {msg}", nl=False)
    sys.stdout.flush()


def handle_train(config: TrainConfig) -> None:
    """Execute a training script and print per-node progress + final metrics.

    The script must define a ``TrainingJob`` instance named ``job`` with a
    ``.run()`` method.  Exits with ``SystemExit(1)`` on any of: missing
    file, failed safety validation, import error, missing ``job``
    variable, or training failure.
    """
    import importlib.util

    filepath = config.training_script
    if not filepath.exists():
        click.echo(f"Error: Training script not found: {filepath}", err=True)
        raise SystemExit(1)

    click.echo(f"Running training script: {filepath}")

    # Validate the script for dangerous patterns before execution
    from haute._sandbox import UnsafeCodeError, validate_user_code

    try:
        validate_user_code(read_user_text(filepath), allow_imports=True)
    except UnsafeCodeError as e:
        click.echo(f"Error: Training script failed safety validation: {e}", err=True)
        raise SystemExit(1)

    # Load the script as a module
    spec = importlib.util.spec_from_file_location("training_script", filepath)
    if spec is None or spec.loader is None:
        click.echo(f"Error: Cannot load {filepath}", err=True)
        raise SystemExit(1)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as e:
        click.echo(f"Error executing script: {e}", err=True)
        raise SystemExit(1)

    # Find the TrainingJob instance
    job = getattr(mod, "job", None)
    if job is None:
        click.echo("Error: No 'job' variable found in training script.", err=True)
        click.echo("  The script should define: job = TrainingJob(...)", err=True)
        raise SystemExit(1)

    try:
        result = job.run(progress=_progress)
        click.echo()  # newline after progress bar
        click.echo(f"\n  \u2713 Model saved to: {result.model_path}")
        # ``test_rows`` is a legacy field name that carries the validation-set
        # count (see TrainResult); label it truthfully for the user.
        click.echo(
            f"  \u2713 Train: {result.train_rows:,} rows, Validation: {result.test_rows:,} rows"
        )
        n_cat = len(result.cat_features)
        click.echo(f"  \u2713 Features: {len(result.features)} ({n_cat} categorical)")
        click.echo("\n  Metrics:")
        for name, value in result.metrics.items():
            click.echo(f"    {name}: {value:.4f}")
    except Exception as e:
        click.echo(f"\n  \u2717 Training failed: {e}", err=True)
        raise SystemExit(1)


@click.command()
@click.argument("training_script")
def train(training_script: str) -> None:
    """Run a model training job from a training script.

    The script should define a ``TrainingJob`` instance named ``job``
    with a ``.run()`` method (as generated by ``haute export``).

    \b
    Examples:
      haute train training/frequency.py
      haute train train_severity.py
    """
    config = TrainConfig(training_script=Path(training_script))
    handle_train(config)
