#!/usr/bin/env python3
"""Regenerate the sanitizer parity fixture from the backend implementation.

The fixture ``frontend/src/utils/__tests__/sanitizeParity.fixture.json`` pins
``frontend/src/utils/sanitizeName.ts`` to the backend
``haute._graph_utils._sanitize_func_name`` (vitest asserts the TS side,
``tests/test_sanitize_parity_fixture.py`` asserts the Python side — a change
to either implementation fails its leg until the pair is realigned).

This script is the single source of BOTH the input corpus (``_INPUTS`` below)
and the backend-derived expected outputs: ``build_fixture()`` recomputes every
pair from the CURRENT backend sanitizer, and the pytest gate asserts the
on-disk fixture equals ``canonical(build_fixture())`` byte-for-byte — so
neither the expected outputs NOR the corpus itself can drift or shrink
silently (previously the corpus lived only in the fixture, so deleting
edge-case rows kept both suites green).  After an intentional backend
sanitizer change:

    python3 scripts/regen_sanitize_parity_fixture.py

then update ``sanitizeName.ts`` until vitest is green again.  To extend
coverage, append inputs to ``_INPUTS`` and rerun.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from haute._graph_utils import _sanitize_func_name  # noqa: E402

FIXTURE = ROOT / "frontend" / "src" / "utils" / "__tests__" / "sanitizeParity.fixture.json"

# The researched input corpus.  Order is load-bearing (the fixture is asserted
# byte-for-byte); append new cases at the end.
_INPUTS: list[str] = [
    "False",
    "False!",
    "  False  ",
    "False node",
    "FALSE",
    "myFalse",
    "None",
    "None!",
    "  None  ",
    "None node",
    "NONE",
    "myNone",
    "True",
    "True!",
    "  True  ",
    "True node",
    "TRUE",
    "myTrue",
    "and",
    "and!",
    "  and  ",
    "and node",
    "AND",
    "myand",
    "as",
    "as!",
    "  as  ",
    "as node",
    "AS",
    "myas",
    "assert",
    "assert!",
    "  assert  ",
    "assert node",
    "ASSERT",
    "myassert",
    "async",
    "async!",
    "  async  ",
    "async node",
    "ASYNC",
    "myasync",
    "await",
    "await!",
    "  await  ",
    "await node",
    "AWAIT",
    "myawait",
    "break",
    "break!",
    "  break  ",
    "break node",
    "BREAK",
    "mybreak",
    "class",
    "class!",
    "  class  ",
    "class node",
    "CLASS",
    "myclass",
    "continue",
    "continue!",
    "  continue  ",
    "continue node",
    "CONTINUE",
    "mycontinue",
    "def",
    "def!",
    "  def  ",
    "def node",
    "DEF",
    "mydef",
    "del",
    "del!",
    "  del  ",
    "del node",
    "DEL",
    "mydel",
    "elif",
    "elif!",
    "  elif  ",
    "elif node",
    "ELIF",
    "myelif",
    "else",
    "else!",
    "  else  ",
    "else node",
    "ELSE",
    "myelse",
    "except",
    "except!",
    "  except  ",
    "except node",
    "EXCEPT",
    "myexcept",
    "finally",
    "finally!",
    "  finally  ",
    "finally node",
    "FINALLY",
    "myfinally",
    "for",
    "for!",
    "  for  ",
    "for node",
    "FOR",
    "myfor",
    "from",
    "from!",
    "  from  ",
    "from node",
    "FROM",
    "myfrom",
    "global",
    "global!",
    "  global  ",
    "global node",
    "GLOBAL",
    "myglobal",
    "if",
    "if!",
    "  if  ",
    "if node",
    "IF",
    "myif",
    "import",
    "import!",
    "  import  ",
    "import node",
    "IMPORT",
    "myimport",
    "in",
    "in!",
    "  in  ",
    "in node",
    "IN",
    "myin",
    "is",
    "is!",
    "  is  ",
    "is node",
    "IS",
    "myis",
    "lambda",
    "lambda!",
    "  lambda  ",
    "lambda node",
    "LAMBDA",
    "mylambda",
    "nonlocal",
    "nonlocal!",
    "  nonlocal  ",
    "nonlocal node",
    "NONLOCAL",
    "mynonlocal",
    "not",
    "not!",
    "  not  ",
    "not node",
    "NOT",
    "mynot",
    "or",
    "or!",
    "  or  ",
    "or node",
    "OR",
    "myor",
    "pass",
    "pass!",
    "  pass  ",
    "pass node",
    "PASS",
    "mypass",
    "raise",
    "raise!",
    "  raise  ",
    "raise node",
    "RAISE",
    "myraise",
    "return",
    "return!",
    "  return  ",
    "return node",
    "RETURN",
    "myreturn",
    "try",
    "try!",
    "  try  ",
    "try node",
    "TRY",
    "mytry",
    "while",
    "while!",
    "  while  ",
    "while node",
    "WHILE",
    "mywhile",
    "with",
    "with!",
    "  with  ",
    "with node",
    "WITH",
    "mywith",
    "yield",
    "yield!",
    "  yield  ",
    "yield node",
    "YIELD",
    "myyield",
    "_",
    "case",
    "match",
    "type",
    "my node",
    "my-node",
    "my node-name here",
    "  padded  ",
    "a b c d",
    "a-b-c-d",
    "tab\tsep",
    "new\nline",
    "v\xa0space",
    "em\u2003space",
    "trailing-",
    "-leading",
    "mid--dash",
    "  ",
    "\t\n ",
    "a   b",
    "snake_case_already",
    "kebab-case-name",
    "hello@world!",
    "rate(%)",
    "col#1&2",
    "@#$%",
    "!1foo",
    "a.b.c",
    "x/y\\z",
    "{json}",
    "[list]",
    "<tag>",
    "a;b:c",
    "100%",
    "$price",
    "naïve?",
    "quote'd",
    'dou"ble',
    "back`tick",
    "x\x00y",
    "x\x7fy",
    "123abc",
    "0_start",
    "abc123",
    "_private",
    "9",
    "007bond",
    "3.14",
    "café",
    "caf",
    "cafó",
    "用户1",
    "naïve",
    "Москва",
    "Ω",
    "ε0",
    "a😀b",
    "😀",
    "🇬🇧flag",
    "ümlaut",
    "ﬀ ligature",
    "①②③",
    "Zürich",
    "São_Paulo",
    "façade",
    "über-cool",
    "λambda",
    "１２３",
    "x²",
    "Ⅰroman",
    "\tlead-tab",
    "trail-tab\t",
    "\nlead-nl",
    "trail-nl\n",
    "\rcr\r",
    "\x0bvtab\x0b",
    "\x0cff\x0c",
    "\xa0nbsp\xa0",
    "\u3000ideospace\u3000",
    "\u200bzwsp\u200b",
    "\ufeffbom\ufeff",
    "\u1680ogham\u1680",
    "\u2028lsep\u2028",
    "\u2029psep\u2029",
    "  \t \n  mixedpad  \r\t  ",
    "\xa0\xa0  spaced",
    "a\tb",
    "a\nb",
    "a\rb",
    "a\x0bb",
    "a\x0cb",
    "a\xa0b",
    "a\u3000b",
    "a\u200bb",
    "a\ufeffb",
    "a b\tc d",
    "node_False",
    "False_node",
    "node_None",
    "None_node",
    "node_True",
    "True_node",
    "node_and",
    "and_node",
    "node_as",
    "as_node",
    "node_assert",
    "assert_node",
    "node_async",
    "async_node",
    "node_await",
    "await_node",
    "node_break",
    "break_node",
    "node_class",
    "class_node",
    "node_continue",
    "continue_node",
    "node_def",
    "def_node",
    "node_del",
    "del_node",
    "node_elif",
    "elif_node",
    "node_else",
    "else_node",
    "node_except",
    "except_node",
    "node_finally",
    "finally_node",
    "node_for",
    "for_node",
    "node_from",
    "from_node",
    "node_global",
    "global_node",
    "node_if",
    "if_node",
    "node_import",
    "import_node",
    "node_in",
    "in_node",
    "node_is",
    "is_node",
    "node_lambda",
    "lambda_node",
    "node_nonlocal",
    "nonlocal_node",
    "node_not",
    "not_node",
    "node_or",
    "or_node",
    "node_pass",
    "pass_node",
    "node_raise",
    "raise_node",
    "node_return",
    "return_node",
    "node_try",
    "try_node",
    "node_while",
    "while_node",
    "node_with",
    "with_node",
    "node_yield",
    "yield_node",
    "my_node",
    "my_node_name_here",
    "padded",
    "a_b_c_d",
    "tabsep",
    "newline",
    "v_xa0_space",
    "em_x2003_space",
    "trailing_",
    "_leading",
    "mid__dash",
    "unnamed_node",
    "a___b",
    "kebab_case_name",
    "helloworld",
    "rate",
    "col12",
    "node_1foo",
    "abc",
    "xyz",
    "json",
    "list",
    "tag",
    "node_100",
    "price",
    "na_xef_ve",
    "quoted",
    "double",
    "backtick",
    "xy",
    "node_123abc",
    "node_0_start",
    "node_9",
    "node_007bond",
    "node_314",
    "caf_xe9_",
    "caf_xf3_",
    "_x7528__x6237_1",
    "_x41c__x43e__x441__x43a__x432__x430_",
    "_x3a9_",
    "_x3b5_0",
    "a_x1f600_b",
    "_x1f600_",
    "_x1f1ec__x1f1e7_flag",
    "_xfc_mlaut",
    "_xfb00__ligature",
    "_x2460__x2461__x2462_",
    "Z_xfc_rich",
    "S_xe3_o_Paulo",
    "fa_xe7_ade",
    "_xfc_ber_cool",
    "_x3bb_ambda",
    "_xff11__xff12__xff13_",
    "x_xb2_",
    "_x2160_roman",
    "lead_tab",
    "trail_tab",
    "lead_nl",
    "trail_nl",
    "cr",
    "vtab",
    "ff",
    "nbsp",
    "ideospace",
    "_x200b_zwsp_x200b_",
    "_xfeff_bom_xfeff_",
    "ogham",
    "lsep",
    "psep",
    "mixedpad",
    "spaced",
    "ab",
    "a_xa0_b",
    "a_x3000_b",
    "a_x200b_b",
    "a_xfeff_b",
    "a_bc_d",
    "",
    " ",
    "\xa0",
    "___",
    "a",
]


def build_fixture() -> list[list[str]]:
    return [[inp, _sanitize_func_name(inp)] for inp in _INPUTS]


def canonical(pairs: list[list[str]]) -> str:
    return json.dumps(pairs, ensure_ascii=False)


if __name__ == "__main__":
    FIXTURE.write_text(canonical(build_fixture()), encoding="utf-8")
    print(f"regenerated {len(_INPUTS)} pairs -> {FIXTURE.relative_to(ROOT)}")
